apiVersion: v1
kind: Service
metadata:
  labels:
    app: shared-space
  name: shared-space
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: '5000'
    port: 5000
  selector:
    app: shared-space