apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Namespace }}-cert
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: tls-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
  - {{ .Values.ingress.host | quote }}
  issuerRef:
    name: {{ .Values.ingress.tls.clusterIssuerName | quote }}
    kind: ClusterIssuer