apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: project-ingress
  namespace: {{ .Release.Namespace | quote}}
spec: 
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - backend:
          serviceName: user-gateway
          servicePort: 4180