apiVersion: v1
kind: ConfigMap
metadata:
  name: user-apps-html
  namespace: {{ .Release.Namespace | quote }}
data:
  # yamllint disable rule:line-length
  index.html: |
    <!DOCTYPE html>
    <head>
      <meta charset="UTF-8">
    </head>
    <body>
      <ul>
        <li><a href="./airflow/">Airflow</a></li>
        <li><a href="./browser/">Browser</a></li>
        <li><a href="./code/">Code</a></li>
        <li><a href="./jupyter/">Jupyter</a></li>
      </ul>
        <p>
          Docker Registry: raphael-bos.dev.project.raizen.ai
        </p>
        <p>
          Username: raphael-bos
        </p>
        <p>
          Password: <button onclick=copyToClipboard() >Copy to clipboard</button>
          <input id="password" type="text" style="opacity:0;width:0;">
        </p>
      <script>
        function onLoad(){
          fetch("./password").then(function(response) {
            response.text().then(function(password){
              document.getElementById('password').value = password;
            })
          });
        }

        function copyToClipboard() {
          var copyText = document.getElementById("password");
          copyText.select();
          copyText.setSelectionRange(0, 99999);
          document.execCommand("copy");
        }
        onLoad();
      </script>
    </body>