apiVersion: v1
kind: ConfigMap
metadata:
  name: user-apps-html
  namespace: {{ .Release.Namespace | quote }}
data:
  # yamllint disable rule:line-length
  index.html: |
    <!DOCTYPE html>
    <head>
      <meta charset="UTF-8">
    </head>
    <body>
      <ul>
        <li><a href="./airflow/">Airflow</a></li>
        <li><a href="./browser/">Browser</a></li>
        <li><a href="./code/">Code</a></li>
        <li><a href="./jupyter/">Jupyter</a></li>
      </ul>
    </body>