# Default values for dev-env-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

users:
  - raphael-bos
  - guifneves

oauth:
  proxyProvider: github
  cookieSecret: someSecret
  clientId: someId
  clientSecret: someSecret
  emailDomains: '*'
  redirectUrl: https://dev.project.raizen.ai/oauth2/callback

applications:
  airflow:
    image: raizenanalyticsdev.azurecr.io/airflow-base
    tag: latest
  vscode:
    image: codercom/code-server
    args: ['code-server', '--auth', 'none', '--bind-addr', '0.0.0.0:29901', '.']
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
  jupyter:
    image: jupyter/datascience-notebook
    args: ["jupyter", "lab", "--ip", "0.0.0.0", "--NotebookApp.token=''", "--NotebookApp.base_url=/jupyter", "--port", "29902"]
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
  mlflow:
    image: raizenanalyticsdev.azurecr.io/mlflowz
  

ingress:
  host: dev.project.raizen.ai
  tls:
    clusterIssuerName: letsencrypt-prod

ssh:
  clientDownloadLink: https://github.com/raizen-analytics-ldt/helm-charts/releases

imagePullSecrets:
  - name: acr-secret


# nodeSelector:
  # key: value
  
# tolerations:
#   - key: "key"
#     operator: "Equal"
#     value: "value"
#     effect: "NoSchedule"

volumes:
  disk:
    size: 32Gi
    storageClassName: default
  file:
    size: 500Mi
    storageClassName: azurefile